classdef noise_profile_meas < noise_profile
    methods

        function obj = noise_profile_meas(meas_jitter)
            params = struct(...
                'delta_f0', 0, ...
                'alpha', 0, ...
                'sigma_rw', 0, ...
                'sigma_jitter', meas_jitter, ...
                't0', 0 ...
             );
            obj@noise_profile(params);
        end

        function meas_noise = measurementNoise(obj)
            meas_noise = randn * obj.sigma_jitter;
        end
    end
end
