function [r1, r2] = generate_position_functions(params1, params2)
% params1 and params2 are structs with fields: r (radius), i (inclination), theta0 (initial anomaly)

mu = 3.986004418e14; % gravitational constant [m^3/s^2]
omega1 = sqrt(mu / params1.r^3);
omega2 = sqrt(mu / params2.r^3);

r1 = @(t) params1.r * [...
    cos(omega1*t + params1.theta0); ...
    sin(omega1*t + params1.theta0)*cos(params1.i); ...
    sin(omega1*t + params1.theta0)*sin(params1.i)];

r2 = @(t) params2.r * [...
    cos(omega2*t + params2.theta0); ...
    sin(omega2*t + params2.theta0)*cos(params2.i); ...
    sin(omega2*t + params2.theta0)*sin(params2.i)];
end
